# Generated by Django 4.0.2 on 2022-02-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='post.jpg', upload_to='profile_pics/cover/'),
        ),
    ]
